# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Peters Website
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# CONFIGURATION OPTIONS
# =====================
#default collections_dir: .   
#default data_dir: _data
#sass:              # default
#  sass_dir: _sass  # default
#collections:       # default
#  posts:           # default
#    output: true   # default
#default markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#default whitelist: []
#default plugins: []
#default highlighter         : rouge
#default excerpt_separator   : "\n\n"
#default permalink           : date
#default paginate_path       : /page:num
#
#liquid:
#  error_mode        : warn
#  strict_filters    : false
#  strict_variables  : false
#
#default markdown: kramdown
#kramdown:
#  auto_ids          : true
#  entity_output     : as_char
#  toc_levels        : [1, 2, 3, 4, 5, 6]
#  smart_quotes      : lsquo,rsquo,ldquo,rdquo
#  input             : GFM   # default input: GFM   # (GitHub Flavored Markdown)
#  hard_wrap         : false
#  footnote_nr       : 1
#  show_warnings     : false

# GLOBAL CONFIGURATION

# Change the directory where Jekyll will read files
#source: DIR   # default source: .

# Change the directory where Jekyll will write files
#destination: DIR   # default destination: ./_site 

# Disable non-whitelisted plugins, caching to disk, and ignore symbolic links.
#safe: BOOL   # default safe: false

# Disable caching of content to disk in order to skip creating a .jekyll-cache or similar directory at the source to avoid interference with virtual environments and third-party directory watchers. Caching to disk is always disabled in safe mode.
#disable_disk_cache: BOOL

# Jekyll 4.0 started allowing themes to bundle a _config.yml to simplify theme-onboarding for new users. In the unfortunate situation that importing a bundled theme configuration messes up the merged site-configuration, the user can configure Jekyll to not import the theme-config entirely.
#ignore_theme_config: BOOL

# In Jekyll 4, user-provided entries get added to the default exclusion list and the `include` option can be used to override the default exclusion list entries.
#exclude: [DIR, FILE, ...]   # default exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]   # default created by "jekyll new"

# Force inclusion of directories and/or files in the conversion. .htaccess is a good example since dotfiles are excluded by default. With Jekyll 4, the `include` configuration option entries override the `exclude` option entries.
#include: [DIR, FILE, ...]   # default include: [".htaccess"]   

# When clobbering the site destination, keep the selected files. Useful for files that are not generated by jekyll; e.g. files or assets that are generated by your build tool. The paths are relative to the destination.
#keep_files: [DIR, FILE, ...]   # default keep_files: [".git", ".svn"]

# Set the time zone for site generation. This sets the TZ environment variable, which Ruby uses to handle time and date creation and manipulation. Any entry from the IANA Time Zone Database is valid, e.g. America/New_York. A list of all available values can be found here. When serving on a local machine, the default time zone is set by your operating system. But when served on a remote host/server, the default time zone depends on the server's setting or location.
#timezone: TIMEZONE   # default timezone: null

# Set the encoding of files by name (only available for Ruby 1.9 or later). Available encodings can be shown by the command ruby -e 'puts Encoding::list.join("\n")'.
#encoding: ENCODING   # default encoding: "utf-8"

# Set defaults for front matter variables. The defaults key holds an array of scope/values pairs that define what defaults should be set for a particular file path, and optionally, a file type in that path - e. g. the default layout for all pages and posts:
#defaults:      # default defaults: []
#  -
#    scope:
#      path: ""      # an empty string here means all files in the project
#      type: "posts" # available: "pages", "posts", "drafts" or any collection in your site. While type is optional, you must specify a value for path when creating a scope/values pair.
#    values:         # can be overridden in Front Matter
#      layout: "post"
#      abc: "xyz"    # can be accessed in liquid by {{ page.abc }}
#  -
#    scope:
#      path: "special/*/special.html" # Globbing with asterikx: All "special.html" in all subfolders of "special"
#    values:
#      layout: "special"

# BUILD COMMAND OPTIONS

# Specify plugin directories instead of using _plugins/ automatically.
#plugins_dir: [ DIR1,... ]   # default plugins_dir: _plugins 

# Specify layout directory instead of using _layouts/ automatically.
#layouts_dir: DIR   # default layouts_dir: _layouts

# Process and render draft posts.
#show_drafts: BOOL   # default show_drafts: null

# Publish posts or collection documents with a future date.
#future: BOOL   # default future: false

# Render posts that were marked as unpublished.
#unpublished: BOOL   # default = false

# Produce an index for related posts. Requires the classifier-reborn plugin.
#lsi: BOOL   # default lsi: false

# Limit the number of posts to parse and publish.
#limit_posts: NUM

# Force watch to use polling.
#force_polling: BOOL

# Print verbose output.
#verbose: BOOL   # default verbose: false

# Silence the normal output from Jekyll during a build.
#quiet: BOOL   # default quiet: false

# Enable the experimental incremental build feature. Incremental build only re-builds posts and pages that have changed, resulting in significant performance improvements for large sites, but may also break site generation in certain cases.
#incremental: BOOL   # default = false

# Generate a Liquid rendering profile to help you identify performance bottlenecks.
#profile: BOOL

#Cause a build to fail if there is a YAML syntax error in a page's front matter.
#strict_front_matter: BOOL   # default strict_front_matter: false

#Serve the website from the given base URL.
#baseurl: URL   # default baseurl: ""

# SERVE COMMAND OPTIONS

#Listen on the given port.
#port: PORT   # default port: 4000

#Listen at the given hostname. The default is `localhost`.
#host: HOSTNAME   # default host: 127.0.0.1

#Reload a page automatically on the browser when its content is edited.
#livereload: BOOL

#File glob patterns for LiveReload to ignore. Ensure that patterns are quoted when passed via the command-line to deter your shell from expanding them.
#Note: The given glob patterns are matched against the relative_path attribute of the processed resource. In the event Jekyll reloads a relative_path matching the pattern in spite of being quoted, try listing the pattern(s) under the config file option key.
#livereload_ignore: [ GLOB1,... ]

#Minimum/Maximum delay before automatically reloading page.
#livereload_min_delay: SECONDS
#livereload_max_delay: SECONDS

#Port for LiveReload to listen on.
#livereload_port: PORT

#Open the site's URL in the browser.
#open_url: BOOL

#Detach the server from the terminal.
#detach: BOOL   # default detach: false

#Skips the initial site build which occurs before the server is started.
#skip_initial_build: BOOL

#Show a directory listing instead of loading your index file.
#show_dir_listing: BOOL   # default show_dir_listing: false